spring.application.name=proposta-app

spring.datasource.url=jdbc:postgresql://localhost:5432/proposta_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

rabbitmq.propostapendente.exchange=proposta-pendente.ex
rabbitmq.propostaconcluida.exchange=proposta-concluida.ex
rabbitmq.queue.proposta.concluida=proposta-concluida.ms-proposta